# Generated by Django 6.0.2 on 2026-02-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='notes',
            new_name='maintenance_notes',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='in_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='maintenance_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
